# Generated by Django 5.2 on 2025-04-08 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='comment_post_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='post_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['comment', 'created_at'], name='reply_comment_created_idx'),
        ),
    ]
