# Generated by Django 5.2 on 2025-05-08 14:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('fire_count', models.PositiveIntegerField(default=0)),
                ('heart_count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Optional image', null=True, upload_to='moments/')),
                ('video', models.FileField(blank=True, help_text='Optional video (MP4 recommended)', null=True, upload_to='moments/')),
                ('youtube_link', models.URLField(blank=True, help_text='Optional YouTube link', null=True)),
                ('interests', models.JSONField(help_text="List of interest tags, e.g. ['Drawing', 'Chess']")),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('activity_count', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_moments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeartReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.moment')),
            ],
        ),
        migrations.CreateModel(
            name='FireReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.moment')),
            ],
        ),
        migrations.CreateModel(
            name='MomentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moments.moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MomentPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pings', to=settings.AUTH_USER_MODEL)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='moments.moment')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MomentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='moments.momentcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='moment',
            index=models.Index(fields=['location'], name='moments_mom_locatio_b315bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='heartreaction',
            unique_together={('user', 'moment')},
        ),
        migrations.AlterUniqueTogether(
            name='firereaction',
            unique_together={('user', 'moment')},
        ),
        migrations.AlterUniqueTogether(
            name='momentping',
            unique_together={('moment', 'from_user', 'to_user')},
        ),
    ]
