# Generated by Django 5.2 on 2025-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_momentflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='flag_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
