# Generated by Django 5.2 on 2025-05-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0003_moment_flag_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedMoment',
            fields=[
            ],
            options={
                'verbose_name': 'Flagged Moment',
                'verbose_name_plural': 'Flagged Moments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('moments.moment',),
        ),
    ]
