EUROPEAN_LANGUAGES = [
    ('en', 'English'),
    ('de', 'German'),
    ('fr', 'French'),
    ('es', 'Spanish'),
    ('it', 'Italian'),
    ('nl', 'Dutch'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese'),
    ('ru', 'Russian'),
    ('tr', 'Turkish'),
    ('ro', 'Romanian'),
    ('el', 'Greek'),
    ('sv', 'Swedish'),
    ('cs', 'Czech'),
    ('hu', 'Hungarian'),
    ('bg', 'Bulgarian'),
    ('da', 'Danish'),
    ('fi', 'Finnish'),
    ('no', 'Norwegian'),
    ('sk', 'Slovak'),
    ('hr', 'Croatian'),
    ('sr', 'Serbian'),
    ('lt', 'Lithuanian'),
    ('lv', 'Latvian'),
    ('et', 'Estonian'),
]
