# Generated by Django 5.2 on 2025-05-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_image_message_read_message_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
    ]
