# Generated by Django 5.2 on 2025-05-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_last_message_chatroom_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='youtube_link',
        ),
    ]
