# Generated by Django 5.2 on 2025-04-08 18:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('pronouns', models.CharField(blank=True, choices=[('he/him', 'He/Him'), ('she/her', 'She/Her'), ('they/them', 'They/Them')], max_length=20, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('show_date_of_birth', models.BooleanField(default=True)),
                ('show_gender', models.BooleanField(default=True)),
                ('show_pronouns', models.BooleanField(default=True)),
                ('show_phone_number', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=False)),
                ('show_main_language', models.BooleanField(default=True)),
                ('show_sublanguage', models.BooleanField(default=True)),
                ('show_bio', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('main_language', models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian'), ('nl', 'Dutch'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('tr', 'Turkish'), ('ro', 'Romanian'), ('el', 'Greek'), ('sv', 'Swedish'), ('cs', 'Czech'), ('hu', 'Hungarian'), ('bg', 'Bulgarian'), ('da', 'Danish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('sk', 'Slovak'), ('hr', 'Croatian'), ('sr', 'Serbian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('et', 'Estonian')], max_length=5, null=True)),
                ('sublanguage', models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian'), ('nl', 'Dutch'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('tr', 'Turkish'), ('ro', 'Romanian'), ('el', 'Greek'), ('sv', 'Swedish'), ('cs', 'Czech'), ('hu', 'Hungarian'), ('bg', 'Bulgarian'), ('da', 'Danish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('sk', 'Slovak'), ('hr', 'Croatian'), ('sr', 'Serbian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('et', 'Estonian')], max_length=5, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
