# Generated by Django 5.2 on 2025-05-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_friendrequest_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('message', 'Message'), ('ping', 'Pinged into Moment'), ('other', 'Other')], max_length=20),
        ),
    ]
